[build]
  command = "curl https://prod-files-secure.s3.us-west-2.amazonaws.com/684016eb-2091-4956-b4b6-d55e981fa1c2/1d5f4fef-080f-4baa-a3ff-1d5189f5a54b/Untitled.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIAT73L2G45FSPPWI6X%2F20241208%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20241208T025619Z&X-Amz-Expires=3600&X-Amz-Signature=d4d62b0b0d5e7c91855734dffe97048e761a62993ddefd9c3045b67835099a9d&X-Amz-SignedHeaders=host&x-id=GetObject -o file && bun run generate && bun run build"
  publish = "build/client"

[functions]
  included_files = ["extras/**", "posts/**"]
